### ISSUE TITLE
Wrong Incito version in the Cartfile

### ISSUE THREAD

**Issue by GeorgiDamyanov** [shopgun/shopgun-ios-sdk#36]
It appears that v4.2 of the SDK requires version 0.10 of the Incito framework in the Cartfile, while the Pod specificaiton file requires version 1.0 as a minimum. As a result the Carthage `bootstrap` command fails with the following error:

```
Could not pick a version for github "shopgun/swift-future", due to mutually incompatible requirements:
	~> 0.4.0
	~> 0.3.0 (github "shopgun/incito-ios")
```

**Comment by lozhuf** [comment]
@GeorgiDamyanov Thanks for the feedback! I have bumped the version of the `incito-ios` repo to be 1.0.2 on the develop branch. This should hopefully fix the issue you are seeing. If you are able to, please verify that this is working on your setup.

**Comment by GeorgiDamyanov** [comment]
@lozhuf Thank you, the problem is resolved now. I am closing this issue =)
