### ISSUE TITLE
Crash when handling `.serviceUnavailable` errors 

### ISSUE THREAD

**Issue by GeorgiDamyanov** [shopgun/shopgun-ios-sdk#39]
We started getting crashes when the SDK attempts to handle an error. It appears that the `exclamation-icon` asset is missing. We are currently using the SPM-support branch, so it could be something related to that particular branch.

**Comment by lozhuf** [comment]
Hi @GeorgiDamyanov. Thanks for the heads up! This has now been fixed in the latest commit on the `SPM-support` branch. If you come across any other problems don't hesitate to let us know.
