### ISSUE TITLE
CoreAPI.Requests.getOffers( matchingSearch: ) - bulk option

### ISSUE THREAD

**Issue by PeterAntonsen** [shopgun/shopgun-ios-sdk#7]
Just an possible optimization idea, which will probably also require backend updates - if I have multiple individual searchTerms that I want to find offers for (ie. "Chips", "Cola", etc.), I have to make [x]-number of requests in order to get meaningful results (and keep searchTerm and results entangled). If there was an option to submit an array of searchTerms and the response-offers then contained a property referring to the related searchTerm (or in some other way made it possible to dissect which offers relates to what searchTerm). I could then furfill my task with only one request and then process the response-offers into searchTerm-related objects.

**Comment by lozhuf** [comment]
This isn't really an optimisation we think is worth the backend engineering for. Thanks for the suggestion, though!
